# BANNER
spring.banner.location: classpath:banner.txt

# GITHUB CREDENTIALS
git:
  username:
  password:

spring:
  cloud:
   config:
    server:
     git:
      uri: https://github.com/Lylio/config-repo
      username: ${git.username}
      password: ${git.password}


# EMBEDDED SERVER CONFIGURATION
server.port: 8888
