spring.application.name: chinook-services

git:
  username:
  password:

spring:
  cloud:
   config:
    server:
     git:
      uri: https://github.com/Lylio/config-repo
      username: ${git.username}
      password: ${git.password}

server.port: 8888
