# Pass git credentials to JAR as system variables:
# 1. mvn clean install
# 2. cd target/
# 3. java -jar chinook-0.0.1-SNAPSHOT.jar --git.username=username --git.password=password
# 4. Verify the config has been pulled from https://github.com/Lylio/config-repo
# at http://localhost:8888/application/default

spring.application.name: chinook

git:
  username:
  password:

spring:
  cloud:
   config:
    server:
     git:
      uri: https://github.com/Lylio/config-repo
      username: ${git.username}
      password: ${git.password}

server.port: 8888
